apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002
  selector:
      app: nginx
